version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: myrootpassword
    networks:
      - demo-network
  app:
    build: .
    ports:
      - 8080:6060
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    networks:
      - demo-network
    depends_on:
      - db
networks:
  demo-network: