FROM adoptopenjdk/openjdk11:alpine-slim AS builder

WORKDIR /app

COPY . /app

RUN ./mvnw dependency:go-offline

COPY src/ /app/src/
RUN ./mvnw clean package -DskipTests

# Application stage
FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar

ENTRYPOINT ["java","-jar","/app.jar"]